FROM alpine:latest AS certgen
WORKDIR /certs
RUN apk add --no-cache openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout server.key \
    -out    server.crt \
    -subj   "/C=US/ST=State/L=City/O=Org/OU=Dev/CN=localhost"


FROM httpd:2.4
WORKDIR /usr/local/apache2/conf
COPY --from=certgen /certs         certs
COPY                httpd-2.4.conf httpd.conf
COPY                proxy.conf     extra/proxy.conf
COPY                httpd-ssl.conf extra/httpd-ssl.conf

# vim: ft=dockerfile
